import axios from "axios";
import querystring from "querystring";

const params = querystring.stringify({
  region: "19",
  province: "LC",
  town: "Morterone",
  carb: "1-x",
  ordPrice: "asc",
});

const config = {
  headers: {
    "Content-Type": "application/x-www-form-urlencoded",
  },
};

axios
  .post(
    "https://carburanti.mise.gov.it/OssPrezziSearch/ricerca/localita",
    params,
    config
  )
  .then((res) => console.log(res.data));

regions = {
  Marche: 1,
  Abruzzo: 2,
  Basilicata: 3,
  Molise: 4,
  TrentinoAltoAdige: 5,
  Puglia: 6,
  Calabria: 7,
  Campania: 8,
  Lazio: 9,
  Sardegna: 10,
  Sicilia: 11,
  Toscana: 12,
  Piemonte: 13,
  EmiliaRomagna: 14,
  FriuliVeneziaGiulia: 15,
  ValDAosta: 16,
  Veneto: 17,
  Liguria: 18,
  Lombardia: 19,
  Umbria: 20,
};

provinces = {
  AN: "Ancona",
  AP: "Ascoli Piceno",
  FM: "Fermo",
  MC: "Macerata",
  PU: "Pesaro e Urbino",
  CH: "Chieti",
  AQ: "L'Aquila",
  PE: "Pescara",
  TE: "Teramo",
  MT: "Matera",
  PZ: "Potenza",
  CB: "Campobasso",
  IS: "Isernia",
  BZ: "Bolzano",
  TN: "Trento",
  BA: "Bari",
  BT: "Barletta-Andria-Trani",
  BR: "Brindisi",
  FG: "Foggia",
  LE: "Lecce",
  TA: "Taranto",
  CZ: "Catanzaro",
  CS: "Cosenza",
  KR: "Crotone",
  RC: "Reggio Calabria",
  VV: "Vibo Valentia",
  AV: "Avellino",
  BN: "Benevento",
  CE: "Caserta",
  NA: "Napoli",
  SA: "Salerno",
  FR: "Frosinone",
  LT: "Latina",
  RI: "Rieti",
  RM: "Roma",
  VT: "Viterbo",
  CA: "Cagliari",
  CI: "Carbonia-Iglesias",
  VS: "Medio Campidano",
  NU: "Nuoro",
  OG: "Ogliastra",
  OT: "Olbia-Tempio",
  OR: "Oristano",
  SS: "Sassari",
  AG: "Agrigento",
  CL: "Caltanissetta",
  CT: "Catania",
  EN: "Enna",
  ME: "Messina",
  PA: "Palermo",
  RG: "Ragusa",
  SR: "Siracusa",
  TP: "Trapani",
  AR: "Arezzo",
  FI: "Firenze",
  GR: "Grosseto",
  LI: "Livorno",
  LU: "Lucca",
  MS: "Massa-Carrara",
  PI: "Pisa",
  PT: "Pistoia",
  PO: "Prato",
  SI: "Siena",
  AL: "Alessandria",
  AT: "Asti",
  BI: "Biella",
  CN: "Cuneo",
  NO: "Novara",
  TO: "Torino",
  VB: "Verbano-Cusio-Ossola",
  VC: "Vercelli",
  BO: "Bologna",
  FE: "Ferrara",
  FC: "Forlì-Cesena",
  MO: "Modena",
  PR: "Parma",
  PC: "Piacenza",
  RA: "Ravenna",
  RE: "Reggio Emilia",
  RN: "Rimini",
  GO: "Gorizia",
  PN: "Pordenone",
  TS: "Trieste",
  UD: "Udine",
  AO: "Aosta",
  BL: "Belluno",
  PD: "Padova",
  RO: "Rovigo",
  TV: "Treviso",
  VE: "Venezia",
  VR: "Verona",
  VI: "Vicenza",
  GE: "Genova",
  IM: "Imperia",
  SP: "La Spezia",
  SV: "Savona",
  BG: "Bergamo",
  BS: "Brescia",
  CO: "Como",
  CR: "Cremona",
  LC: "Lecco",
  LO: "Lodi",
  MN: "Mantova",
  MI: "Milano",
  MB: "Monza e della Brianza",
  PV: "Pavia",
  SO: "Sondrio",
  VA: "Varese",
  PG: "Perugia",
  TR: "Terni",
};

fuelType = {
  gasoline: "1",
  diesel: "2",
  methane: "3",
  lpg: "4",
};

service = {
  any: "x",
  self: "0",
  served: "1",
};
